### PR TITLE
test

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-grayskull test abc

**Comment by marcelotrevisani** [comment]
@conda-grayskull test abc

**Comment by marcelotrevisani** [comment]
@conda-grayskull new test

**Comment by conda-grayskull** [comment]
All host requirements found:
 - pip
 - python >=3.8
 - setuptools >=30.3.0
 - setuptools-scmAll run requirements found:
 - colorama
 - conda-souschef >=2.1.1
 - pip
 - pkginfo
 - progressbar2 >=3.53.0
 - python >=3.8
 - rapidfuzz >=1.7.1
 - requests
 - ruamel.yaml >=0.16.10
 - ruamel.yaml.jinja2
 - setuptools >=30.3.0
 - stdlib-list

**Comment by conda-grayskull** [comment]
All host requirements found:
 - pip
 - python >=3.8
 - setuptools >=30.3.0
 - setuptools-scm


All run requirements found:
 - colorama
 - conda-souschef >=2.1.1
 - pip
 - pkginfo
 - progressbar2 >=3.53.0
 - python >=3.8
 - rapidfuzz >=1.7.1
 - requests
 - ruamel.yaml >=0.16.10
 - ruamel.yaml.jinja2
 - setuptools >=30.3.0
 - stdlib-list

**Pull request closed without merging**
